### ISSUE TITLE
synced_folder有効時に「sudo: sorry, you must have a tty to run sudo」が発生する

### ISSUE THREAD

**Issue by rynagash** [hironobu-s/vagrant-conoha#4]
```
  config.vm.synced_folder ".", "/vagrant"
```
上記の設定している際に、新規でのインスタンス作成が
```
$ vagrant up --provider=conoha
# 略
Machine booted and ready
```
以降、`DEBUG ssh: Sending SSH keep-alive...`をデバッグログへの表示を繰り返し進まくなってしまいました。

Ctrl+Cを2回押し中断し、`vagrant provision`を実行すると、`rsync`の際に失敗し同時に下記のエラーが表示されます。
```
sudo: sorry, you must have a tty to run sudo
```

sudoresファイルを下記の通り編集することで`rsync`することはできました。
```
$ vagrant ssh

% cat /etc/sudoers
# 略
Defaults   requiretty
Defaults:root requiretty
```

環境：
macOS Sierra `10.12.4`
vagrant version `1.9.4`
vagrant-conoha `0.1.7`
conoha.image  `vmi-centos-7.2-amd64-20gb` (from Vagrantfile)

**Comment by hironobu-s** [comment]
お返事が遅れてすみません。

`vagrant up` で `Sending SSH keep-alive...` がループしてしまうのは、CentOS系を選んだときに時折起きる症状のようで、VPSがDHCPでIPアドレスを取得するのに非常に時間がかかるような現象を確認しています。詳しく調べられていませんが、CentOSのDHCPクライアントとConoHaの基板のDHCPサーバーに依存する問題のようです(Ubuntuでは起きないため)。
これはvagrant-conoha側では解決できないため、社内でフィードバックいたします。

rsyncに失敗する件は、ご報告いただいたとおりttyが要因です。これもCentOS系で発生するようでvagrant-conoha側で対応するか迷ったのですが、0.1.8から[スタートアップスクリプト](https://www.conoha.jp/guide/startupscript.php)が使えるようになっているので、この機能で個別に対応をお願いいたします。
